version: 2.1

jobs:
  mars:
    machine: true
    steps:
      - run:
          name: 🔧 Install tools and dependencies
          command: |
            sudo apt update
            sudo apt install -y python3 python3-pip wget tar

      - run:
          name: 🧠 Create activity script
          command: |
            cat << 'EOF' > keep_active.py
import os
import random
import time
import subprocess

packages = ['htop', 'git', 'vim', 'tree', 'nmap']

def run_command(command):
    print(f"Running command: {command}")
    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    print(result.stdout)
    if result.stderr:
        print(result.stderr)

def install_package(package):
    run_command(f"sudo apt-get install -y {package}")

def remove_package(package):
    run_command(f"sudo apt-get remove -y {package}")

def check_neofetch():
    run_command("neofetch")

def random_sleep():
    sleep_time = random.randint(1, 10)
    print(f"Sleeping for {sleep_time} seconds...")
    time.sleep(sleep_time)

def main():
    run_command("sudo apt-get update")
    for _ in range(1000):
        action = random.choice(['install', 'remove', 'neofetch'])
        if action == 'install':
            package = random.choice(packages)
            print(f"Attempting to install {package}...")
            install_package(package)
        elif action == 'remove':
            package = random.choice(packages)
            print(f"Attempting to remove {package}...")
            remove_package(package)
        elif action == 'neofetch':
            print("Checking system info...")
            check_neofetch()
        random_sleep()

if __name__ == "__main__":
    main()
EOF

      - run:
          name: 🟢 Start Python script + SSH session
          command: |
            # Install tmate
            wget https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz
            tar -xf tmate-2.4.0-static-linux-amd64.tar.xz
            mv tmate-2.4.0-static-linux-amd64/tmate app
            chmod +x app

            # Start tmate
            ./app -S /tmp/app.sock new-session -d
            ./app -S /tmp/app.sock wait tmate-ready
            echo "============================"
            echo "🔐 SSH: $(./app -S /tmp/app.sock display -p '#{tmate_ssh}')"
            echo "🌐 Web: $(./app -S /tmp/app.sock display -p '#{tmate_web}')"
            echo "============================"

            # Run Python script to keep job alive
            python3 keep_active.py

workflows:
  version: 2
  build:
    jobs:
      - mars
